### ISSUE TITLE
Entity not available?

### ISSUE THREAD

**Issue by YanisKyr** [ds2000/homeassistant-fe-tesla#1]
I'm probably doing something wrong but for the love of god, I can't figure out what it is.. Any ideas or pointers?

The error I see is `Entity not available: input_boolean.tesla_charger_menu`

**Comment by AlisterGill** [comment]
You need to create the 3 input boolean entities manually as a helper

**Comment by YanisKyr** [comment]
Thanks for the feedback. I'm not sure _how_ to do that - could you shed some light?

It would be useful to have this bit in the installation guide.

**Comment by ds2000** [comment]
Ah man, I am so sorry, I completely forgot to document those in my readme.Under devices and services, go to helpers and create them there.  I will update the readme as soon as I can.￼​Sent from my iPhoneOn 8 Aug 2023, at 20:42, YanisKyr ***@***.***> wrote:﻿
Thanks for the feedback. I'm not sure how to do that - could you shed some light?
It would be useful to have this bit in the installation guide.
