### ISSUE TITLE
More colors?

### ISSUE THREAD

**Issue by ignacio82** [ds2000/homeassistant-fe-tesla#15]
First, thanks for the great work! Very minor question/request. How hard would it be to have additional colors? For example, a Midnight Silver Metallic (PMNG) model 3.

**Comment by ds2000** [comment]
Its a bit of a pain, I need access to the images of the model 3.  If you screenshot everything that you see in the red folder, I can put them through photoshop and remove the bits that aren't needed from the images.

**Comment by ds2000** [comment]
Or you could try your luck at doing a colour change in photoshop and seeing how that comes out?
