### ISSUE TITLE
Feature Request: Support for Tessie integration

### ISSUE THREAD

**Issue by husnainali09** [ds2000/homeassistant-fe-tesla#20]
Requesting support for Tessie based integration as it doesnt require proxies.

**Comment by ds2000** [comment]
Thanks,
It looks a nice integration.  I'll certainly have a look but you can see
from the last commit I'm a bit buried with other projects at the moment
(garage renovation, house renovation, two kids under 5 etc).
I have quite a few unpublished updates as well that I need to get out there.

**Comment by ds2000** [comment]
Sorry, to get an API key for Tessie needs a subscription
