### ISSUE TITLE
Which folder should I put the images to?

### ISSUE THREAD

**Issue by YanisKyr** [ds2000/homeassistant-fe-tesla#5]
Which one of my folders do the images have to go to?

Do I create a Local at root level (where Blueprints, Config, Themes etc. are)?

**Comment by YanisKyr** [comment]
I figured this one out after all. For the record, the `Tesla` folder needs to go in `/config/www/`.

**Comment by ds2000** [comment]
Sorry for the slow reply, I've got a full time job on the side and two little kids, so catching the requests quickly is tricky.
I'm glad you figured it out :)
