### ISSUE TITLE
Some elements don't display in Gotham font

### ISSUE THREAD

**Issue by YanisKyr** [ds2000/homeassistant-fe-tesla#6]
Any idea how to troubleshoot this one? :)

![image](https://github.com/ds2000/homeassistant-fe-tesla/assets/35373257/c04e796b-e9ff-43f7-8da5-6f1163e9ac35)

![image](https://github.com/ds2000/homeassistant-fe-tesla/assets/35373257/bbd734c4-24cb-4c85-b182-d42d0cc227ae)

**Comment by ds2000** [comment]
Is it just the spacing?  To me it looks like the font isnt working at all?
I have a winter release coming, I've got the seat heating controls working, the temperature up and down and a few other bits.  Just the climate control mode to defrost is left for that panel now :)

**Comment by YanisKyr** [comment]
Are the 'Controls'/'Climate'/'Defrost Car' not in Gotham?

If the next one is coming, there's probably not much value troubleshooting it now I guess.

**Comment by ds2000** [comment]
No, they're image files, literally screenshots snipped from the iPhone.
The next version won't change the gotham issue.
Once I have all the functionality, I hope to bundle it up into a HACs installer and avoid every using this awful yaml file.
