### ISSUE TITLE
What is this icon?

### ISSUE THREAD

**Issue by akeslo** [ds2000/homeassistant-fe-tesla#9]
This is awesome!!

What is this icon for?
<img width="187" alt="image" src="https://github.com/ds2000/homeassistant-fe-tesla/assets/3003773/72db794d-a949-43eb-8de1-b0ad3035a05f">

Thanks!

**Comment by ds2000** [comment]
It’s just a holding icon for if the car is on charge. Once I redo the car images that’ll disappear
